language: java
jdk:
 - oraclejdk8
before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - "sudo apt-get update -qq"
 - "sudo apt-get install oracle-java8-installer"
 - "sudo apt-get install -y ghc"
 - "java -version"
script: 
 - cd Code && mvn test
cache:
 apt: true
 directories:
  - $HOME/.m2
