language: java
jdk: oraclejdk8
before_install:
 - "sudo apt-get update -qq"
 - "sudo apt-get install -y ghc"
script: 
 - cd Code && mvn package
addons:
  artifacts:
    paths:
      - $(ls target/*.jar | tr "\n" ":")
