language: java
jdk:
 - oraclejdk8
 - oraclejdk7
 - openjdk6
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y ghc
script: 
 - cd Code && mvn test
cache:
 apt: true
 directories:
  - $HOME/.m2
